### ISSUE TITLE
Support T61String

### ISSUE THREAD

**Issue by scotloach** [exhuma/puresnmp#71]
I ran into a device that raised this error:
Decoding is not yet implemented on <class 'puresnmp.x690.types.T61String'>

It would be helpful if puresnmp supported that.

**Comment by scotloach** [comment]
On further investigation, I don't think the device is actually returning a T61String, something else is up.  I'll update this when I figure out more.

**Comment by exhuma** [comment]
Interesting. Keep me posted. I have planned a minor change in how the code is written for type-detection. It won't change anything in the core logic, it should just make it easier for debugging. I'm currently working on #70 and will probably tackle this next.

Currently the type-information is split into three fields (See https://github.com/exhuma/puresnmp/blob/aaf10d0986580b36f5d7e9ae315ec998468873e1/puresnmp/x690/util.py#L69). These values will however never be visible verbatim on the network because they are encoded into only one byte. The type-detection however uses the three separate fields, so in the current code-base you only usually see the type-tag (see f.ex.: https://github.com/exhuma/puresnmp/blob/aaf10d0986580b36f5d7e9ae315ec998468873e1/puresnmp/x690/types.py#L373)

This makes it hard to debug the network packets and might give some hints for issues like these.

I am planning to replace the `TAG` variable in types with a simple `TYPE_BYTE` variable or something similar which contains the real byte. This should make it easier to read and debug.

Concerning the `T61String`: This is defined [here](https://github.com/exhuma/puresnmp/blob/aaf10d0986580b36f5d7e9ae315ec998468873e1/puresnmp/x690/types.py#L742) and is missing an implementation of [`decode()`](https://github.com/exhuma/puresnmp/blob/aaf10d0986580b36f5d7e9ae315ec998468873e1/puresnmp/x690/types.py#L170). The reason this is not implemented most likely because I never came across it in the wild. I am currently using `puresnmp` with many thousands of devices and never saw it, so I probably left it as "let's cross that bridge when we get there". 

I have no problems in implementing this as soon as I get around to it. The encoding [is well-known](https://en.wikipedia.org/wiki/ITU_T.61) so decoding should be easy. It's just a matter of finding the time to sit down and do it :)

**Comment by exhuma** [comment]
First part is done: [t61codec](https://pypi.org/project/t61codec/)

**Comment by exhuma** [comment]
Pushed support for T61 strings to the `develop` branch. Will be included in the next release.

**Comment by exhuma** [comment]
How does your application behave if you install the version from the develop branch? It now should no longer complain that T61String is not supported. But considering that you think that it's not related to that data-type I'm curious how your code behaves now with that change.
